import {
    Button,
    GridBox,
    Palette,
    ScrollView,
    VerticalBox,
} from "std-widgets.slint";

import { Entry }            from "../../widgets/entry.slint";
import { RowLabel }         from "../../widgets/row-label.slint";
import { ColumnLabel }      from "../../widgets/column-label.slint";
import { Layout }           from "../../layout.slint";
import { BatteryTabFocus }  from "../../layout.slint";
import { BatteryComputed }  from "./battery-structs.slint";
import { BatteryTotals }    from "./battery-structs.slint";

// Summary tab {{{1
//
// Battery summary
//
export component SummaryTab inherits ScrollView {
    callback lock-all-shell-weights();
    callback unlock-all-shell-weights();

    in-out property <[BatteryComputed]> battery-computed: [];
    in-out property <BatteryTotals>   battery-totals;

    VerticalBox {
        alignment: start;

        GridBox {
            spacing: Layout.grid-spacing;

            // This row exists solely to set the column widths
            Row {
                // These blank widgets are solely so we can set column widths in the
                // first row
                Text { height: 0px; width: Layout.label-width; }
                Text { height: 0px; width: Layout.edit-width; }
                Text { height: 0px; width: Layout.edit-width; }
                Text { height: 0px; width: Layout.edit-width; }
                Text { height: 0px; width: Layout.edit-width; }
                Text { height: 0px; width: Layout.edit-width; }
                Text { height: 0px; width: Layout.edit-width; }
            }

            Row {
                Text { text: "Batteries:"; colspan: 4; font-weight: 700; vertical-alignment: bottom; }
            }

            Row {
                Button { col: 1; colspan: 5; height: Layout.edit-height; text: battery-computed[0].desc; clicked => { BatteryTabFocus.current-index = 1; } }
                Button { rowspan: 2; text: "Lock all\nshell weights"; clicked => { root.lock-all-shell-weights(); } }
            }
            Row {
                Button { col: 1; colspan: 5; height: Layout.edit-height; text: battery-computed[1].desc; clicked => { BatteryTabFocus.current-index = 2; } }
            }
            Row {
                Button { col: 1; colspan: 5; height: Layout.edit-height; text: battery-computed[2].desc; clicked => { BatteryTabFocus.current-index = 3; } }
                Button { rowspan: 2; text: "Unlock all\nshell weights"; clicked => { root.unlock-all-shell-weights(); } }
            }
            Row {
                Button { col: 1; colspan: 5; height: Layout.edit-height; text: battery-computed[3].desc; clicked => { BatteryTabFocus.current-index = 4; } }
            }
            Row {
                Button { col: 1; colspan: 5; height: Layout.edit-height; text: battery-computed[4].desc; clicked => { BatteryTabFocus.current-index = 5; } }
            }

            Row { Text { } }

            Row {
                Text { text: "Weights:"; colspan: 4; font-weight: 700; vertical-alignment: bottom; }
            }

            Row {
                ColumnLabel { col: 1; text: "Main:"; }
                ColumnLabel { text: "2nd:"; }
                ColumnLabel { text: "3rd:"; }
                ColumnLabel { text: "4th:"; }
                ColumnLabel { text: "5th:"; }
                ColumnLabel { text: "Total:"; }
            }

            Row {
                Rectangle { colspan: 7; height: 1px; background:
                Palette.alternate-foreground; }
            }

            Row {
                RowLabel { text: "Guns:"; }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[0].wgt-guns; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[1].wgt-guns; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[2].wgt-guns; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[3].wgt-guns; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[4].wgt-guns; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-totals.wgt-guns; } }
            }
            Row {
                RowLabel { text: "Mounts:"; }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[0].wgt-mounts; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[1].wgt-mounts; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[2].wgt-mounts; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[3].wgt-mounts; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[4].wgt-mounts; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-totals.wgt-mounts; } }
            }
            Row {
                RowLabel { text: "Armour:"; }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[0].wgt-armor; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[1].wgt-armor; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[2].wgt-armor; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[3].wgt-armor; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[4].wgt-armor; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-totals.wgt-armor; } }
            }

            Row {
                Rectangle { colspan: 7; height: 1px; background:
                Palette.alternate-foreground; }
            }

            Row {
                RowLabel { text: "Total (t):"; }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[0].wgt-total; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[1].wgt-total; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[2].wgt-total; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[3].wgt-total; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[4].wgt-total; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-totals.wgt-total; } }
            }

            Row { Text { } }

            Row {
                RowLabel { text: "Broadside (lbs):"; }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[0].broadside-lbs; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[1].broadside-lbs; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[2].broadside-lbs; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[3].broadside-lbs; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[4].broadside-lbs; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-totals.broadside-lbs; } }
            }
            Row {
                RowLabel { text: "Broadside (kg):"; }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[0].broadside-kg; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[1].broadside-kg; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[2].broadside-kg; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[3].broadside-kg; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[4].broadside-kg; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-totals.broadside-kg; } }
            }
            Row {
                RowLabel { text: "Magazine (t):"; }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[0].mag-wgt; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[1].mag-wgt; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[2].mag-wgt; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[3].mag-wgt; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-computed[4].mag-wgt; } }
                Rectangle { border-width: 0px; border-color: Palette.alternate-foreground; Text { text: battery-totals.mag-wgt; } }
            }

        }
    }
}
