import { VerticalBox, StandardButton } from "std-widgets.slint";

// AboutDialog {{{1
//
export component AboutDialog inherits Dialog {
    title: "About " + name;

    in property <string> name: "";
    in property <string> version: "";
    in property <string> about: "";
    in property <string> author: "";
    in property <string> legal: "";

    VerticalBox {
        padding: 16px;
        Text { text: root.name + " " + root.version; horizontal-alignment: center; }
        Text { text: root.about;                     horizontal-alignment: center; }
        Text { text: root.author;                    horizontal-alignment: center; }
        Text { }
        Text { text: root.legal;                     horizontal-alignment: left; font-size: 8pt; }
    }

    StandardButton { kind: ok; }
}
