import { VerticalBox, StandardButton } from "std-widgets.slint";

// AboutDialog {{{1
//
export component AboutDialog inherits Dialog {
    title: "About Sharpie";
    min-width: 300px;
    min-height: 150px;

    VerticalBox {
        alignment: center;
        padding: 16px;
        Text {
            text: "Sharpie\n\nA SpringSharp 3b3 clone";
            horizontal-alignment: center;
        }
    }

    StandardButton { kind: ok; }
}
