// Sharpie main window {{{1
//
import {
    GroupBox,
    HorizontalBox,
    ScrollView,
    TabWidget,
    TextEdit,
    VerticalBox,
} from "std-widgets.slint";

import { StatusBar }    from "widgets/status-bar.slint";
import { HullFields,
         HullComputed,
         HullTab,
         ShipIdentity }   from "tabs/hull.slint";
import { FreeboardTab }   from "tabs/freeboard.slint";
import { TorpedoFields,
         TorpedoDerived } from "tabs/weapons.slint";
import { MineFields,
         MineDerived }    from "tabs/weapons.slint";
import { ASWFields,
         ASWDerived }     from "tabs/weapons.slint";
import { WeightFields }   from "tabs/weapons.slint";
import { GunsTab }        from "tabs/guns/guns.slint";
import { BatteryComputed,
         BatteryFields,
         BatteryTotals }  from "tabs/guns/battery-structs.slint";
import { WeaponsTab }     from "tabs/weapons.slint";
import { ArmorTab,
         ArmorComputed,
         ArmorFields }    from "tabs/armor.slint";
import { EnginesTab,
         EngineFields,
         EngineComputed }  from "tabs/engines.slint";
import { PerfTab,
         PerfFields,
         PerfComputed }   from "tabs/performance.slint";

import { Layout         } from "layout.slint";

export { AboutDialog } from "dialogs/about-dialog.slint";

// Main window {{{1
//
export component MainWindow inherits Window {
    title: "Sharpie";
    preferred-width: Layout.tab-width +
        (root.report-visible ? Layout.report-width : 0px) +
        (root.sidebar-visible ? Layout.sidebar-width: 0px)
        ;
    height: Layout.gui-height;

    in-out property <ShipIdentity> identity;
    in-out property <HullFields> hull-fields;
    in-out property <HullComputed> hull-computed;
    in-out property <image> hull-image;

    in-out property <[TorpedoFields]>  torp-fields;
    in-out property <[TorpedoDerived]> torp-derived;
    in-out property <[MineFields]>     mine-fields;
    in-out property <[MineDerived]>    mine-derived;
    in-out property <[ASWFields]>      asw-fields;
    in-out property <[ASWDerived]>     asw-derived;
    in-out property <WeightFields>     weight-fields;

    in-out property <ArmorFields>      armor-fields;
    in-out property <ArmorComputed>    armor-computed;

    in-out property <EngineFields>     engine-fields;
    in-out property <EngineComputed>   engine-computed;

    in-out property <PerfFields>       perf-fields;
    in-out property <PerfComputed>     perf-computed;

    in-out property <BatteryFields>     battery0-fields;
    in-out property <BatteryFields>     battery1-fields;
    in-out property <BatteryFields>     battery2-fields;
    in-out property <BatteryFields>     battery3-fields;
    in-out property <BatteryFields>     battery4-fields;
    in-out property <[BatteryComputed]> battery-computed;
    in-out property <BatteryTotals>     battery-totals;

    in-out property <[string]> asw-type-labels: [];
    in-out property <[string]> bow-labels: [];
    in-out property <[string]> mine-type-labels: [];
    in-out property <[string]> stern-labels: [];
    in-out property <[string]> torp-mount-labels: [];
    in-out property <[string]> bh-kind-labels: [];
    in-out property <[string]> deck-kind-labels: [];

    in-out property <[string]> gun-type-labels: [];
    in-out property <[string]> mount-type-labels: [];
    in-out property <[string]> gun-layout-labels: [];
    in-out property <[string]> gun-distribution-labels: [];

    in-out property <[string]> length-small-labels: [];
    in-out property <[string]> length-long-labels: [];

    in-out property <[string]> weights-labels: [];

    in-out property <string> report-str: "Load or create a ship";
    in-out property <string> notes-str;
    in-out property <bool> report-visible: false;
    in-out property <bool> sidebar-visible: false;

    // Menu callbacks
    callback load-ship();
    callback save-ship();
    callback convert-ship();
    callback clear-ship();
    callback exit-app();
    callback toggle-report();
    callback toggle-sidebar();
    callback show-about();

    // Other callbacks
    callback field-edited();
    callback trim-box-edited();
    callback trim-slider-changed();
    callback shafts-edited();
    callback vmax-slider-changed();
    callback power-lock-toggled();
    callback power-recalc();
    callback draft-edited();
    callback depth-lock-toggled();
    callback freeboards-est(which: int);
    callback save-picture();
    callback torp-units-edited(row: int);
    callback mine-units-edited();
    callback asw-units-edited(row: int);
    callback hull-units-edited();
    callback armor-units-edited();
    callback armor-default();
    callback set-all-units(which: int);
    callback gun-units-edited(row: int);
    callback lock-shell-weight-edited(row: int);
    callback lock-all-shell-weights-edited();
    callback unlock-all-shell-weights-edited();
    callback ship-year-edited();

    // Menu bar {{{2
    //
    MenuBar {
        Menu {
            title: "File";
            MenuItem { title: "Open ship";                shortcut: @keys(Control + O);         activated => { root.load-ship(); } }
            MenuItem { title: "Save ship";                shortcut: @keys(Control + S);         activated => { root.save-ship(); } }
            MenuItem { title: "Convert SpringSharp ship"; shortcut: @keys(Control + Shift + O); activated => { root.convert-ship(); } }
            MenuSeparator {}
            MenuItem { title: "Clear all";                                                      activated => { root.clear-ship(); } }
            MenuSeparator {}
            MenuItem { title: "Exit";                                                           activated => { root.exit-app(); } }
        }
        Menu {
            title: "View";
            MenuItem { title: root.report-visible ? "Hide Report" : "Show Report"; shortcut: @keys(Control + R); activated => { root.toggle-report(); } }
            MenuItem { title: root.sidebar-visible ? "Hide Sidebar" : "Show Sidebar"; shortcut: @keys(Alt + S); activated => { root.toggle-sidebar(); } }
        }
        Menu {
            title: "Help";
            MenuItem { title: "About Sharpie"; shortcut: @keys(F1); activated => { root.show-about(); } }
        }
    }

    // Tabs {{{2
    //
    HorizontalBox {
        VerticalLayout {
            TabWidget {
                width: Layout.tab-width;
                Tab {
                    title: "Hull";
                    HullTab {
                        identity <=> root.identity;
                        hull-fields <=> root.hull-fields;
                        hull-computed <=> root.hull-computed;
                        field-edited => { root.field-edited(); }
                        draft-edited => { root.draft-edited(); }
                        hull-units-edited => { root.hull-units-edited(); }
                        ship-year-edited => { root.ship-year-edited(); }
                        length-long-labels <=> root.length-long-labels;
                        set-all-units(which) => { root.set-all-units(which); }
                    }
                }
                Tab {
                    title: "Freeboard";
                    FreeboardTab {
                        hull-image <=> root.hull-image;
                        hull-fields <=> root.hull-fields;
                        bow-labels <=> root.bow-labels;
                        stern-labels <=> root.stern-labels;
                        length-long-labels <=> root.length-long-labels;
                        field-edited => { root.field-edited(); }
                        save-picture => { root.save-picture(); }
                        depth-lock-toggled => { root.depth-lock-toggled(); }
                        set-freeboards(which) => { root.freeboards-est(which); }
                    }
                }
                Tab {
                    title: "Guns";
                    GunsTab {
                        battery0-fields <=> root.battery0-fields;
                        battery1-fields <=> root.battery1-fields;
                        battery2-fields <=> root.battery2-fields;
                        battery3-fields <=> root.battery3-fields;
                        battery4-fields <=> root.battery4-fields;
                        battery-computed <=> root.battery-computed;
                        battery-totals <=> root.battery-totals;
                        gun-type-labels <=> root.gun-type-labels;
                        mount-type-labels <=> root.mount-type-labels;
                        gun-layout-labels <=> root.gun-layout-labels;
                        gun-distribution-labels <=> root.gun-distribution-labels;
                        length-small-labels <=> root.length-small-labels;
                        field-edited => { root.field-edited(); }
                        gun-units-edited(row) => { root.gun-units-edited(row); }
                        lock-shell-weight-toggled(row) => { root.lock-shell-weight-edited(row); }
                        lock-all-shell-weights => { root.lock-all-shell-weights-edited(); }
                        unlock-all-shell-weights => { root.unlock-all-shell-weights-edited(); }
                    }
                }
                Tab {
                    title: "Weapons";
                    WeaponsTab {
                        torp-fields <=> root.torp-fields;
                        torp-derived <=> root.torp-derived;
                        mine-fields <=> root.mine-fields;
                        mine-derived <=> root.mine-derived;
                        asw-fields <=> root.asw-fields;
                        asw-derived <=> root.asw-derived;
                        weight-fields <=> root.weight-fields;
                        asw-type-labels <=> root.asw-type-labels;
                        mine-type-labels <=> root.mine-type-labels;
                        torp-mount-labels <=> root.torp-mount-labels;
                        length-small-labels <=> root.length-small-labels;
                        weights-labels <=> root.weights-labels;
                        field-edited => { root.field-edited(); }
                        torp-units-edited(row) => { root.torp-units-edited(row); }
                        mine-units-edited => { root.mine-units-edited(); }
                        asw-units-edited(row) => { root.asw-units-edited(row); }
                    }
                }
                Tab {
                    title: "Armor";
                    ArmorTab {
                        armor-fields <=> root.armor-fields;
                        armor-computed <=> root.armor-computed;
                        length-small-labels <=> root.length-small-labels;
                        length-long-labels <=> root.length-long-labels;
                        field-edited => { root.field-edited(); }
                        armor-units-edited => { root.armor-units-edited(); }
                        armor-default => { root.armor-default(); }
                        bh-kind-labels <=> root.bh-kind-labels;
                        deck-kind-labels <=> root.deck-kind-labels;
                    }
                }
                Tab {
                    title: "Engines";
                    EnginesTab {
                        engine-fields <=> root.engine-fields;
                        engine-computed <=> root.engine-computed;
                        field-edited => { root.field-edited(); }
                        shafts-edited => { root.shafts-edited(); }
                        vmax-slider-changed => { root.vmax-slider-changed(); }
                        power-lock-toggled => { root.power-lock-toggled(); }
                        power-recalc => { root.power-recalc(); }
                    }
                }
                Tab {
                    title: "Performance";
                    PerfTab {
                        perf-fields <=> root.perf-fields;
                        perf-computed <=> root.perf-computed;
                        field-edited => { root.field-edited(); }
                        trim-box-edited => { root.trim-box-edited(); }
                        trim-slider-changed => { root.trim-slider-changed(); }
                    }
                }
            }
            StatusBar { // {{{2
                status-text: "Composite strength = " + root.perf-computed.str-comp;
            }
        }

        VerticalBox { // Report {{{2
            visible: root.report-visible;
            width: root.report-visible ? Layout.report-width : 0px;
            horizontal-stretch: 0;
            vertical-stretch: 1;

            Text { text: "Report"; font-weight: 900; }

            report := TextEdit { text: root.report_str; read-only: true; }
            StatusBar {
                status-text: "Additional notes—included at end of report and saved to *.ship file:";
            }
            TextEdit {
                height: Layout.gui-height * 0.25;
                text: root.notes_str;
                edited => { root.field-edited(); }
            }
        }

        ScrollView { // Sidebar {{{2
            visible: root.sidebar-visible;
            width: root.sidebar-visible ? Layout.sidebar-width : 0px;
            horizontal-stretch: 0;

            VerticalBox {
                alignment: start;

                Text { text: "Performance"; font-weight: 900; }
                Text { horizontal-alignment: center; text: "Composite strength:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.str-comp; }
                Text { horizontal-alignment: center; text: "Seakeeping:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.seakeeping; }
                Text { horizontal-alignment: center; text: "Stability:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.stability; }
                Text { horizontal-alignment: center; text: "Steadiness:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.steadiness; }
                Text { horizontal-alignment: center; text: "Hull space:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.hull-room + " %"; }
                Text { horizontal-alignment: center; text: "Armor coverage:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.belt-coverage + " %"; }
                Text { horizontal-alignment: center; text: "Work space:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.deck-room + " %"; }

                Text { text: "Displacement:"; font-weight: 700; }
                Text { horizontal-alignment: center; text: "Maximum displacement:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.d-max; }
                Text { horizontal-alignment: center; text: "Normal displacement:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.d-norm; }
                Text { horizontal-alignment: center; text: "Standard displacement:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.d-std; }
                Text { horizontal-alignment: center; text: "Light displacement:"; }
                Text { horizontal-alignment: right; text: root.perf-computed.d-lite; }

                Text { text: "Guns and engines:"; font-weight: 700; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.battery-computed[0].desc; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.battery-computed[1].desc; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.battery-computed[2].desc; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.battery-computed[3].desc; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.battery-computed[4].desc; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.engine-computed.fuel-desc + ","; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.engine-computed.boiler-desc + ","; }
                Text { horizontal-alignment: center; wrap: word-wrap; text: root.engine-computed.drive-desc; }
            }
        }
    }
}
