// Layout constants {{{1
//
export global Layout {
    in property <length> tab-width:     980px;
    in property <length> gui-height:    940px;
    in property <length> report-width:  650px;

    in property <length> edit-width:    100px;
    in property <length> edit-height:    35px;
    in property <length> label-width:   50px;
    in property <length> combo-width:   200px;
    in property <length> grid-spacing:    8px;
}
