name: Create release

on:
  push:
    tags:
      - '**' # includes x/y tags
  workflow_dispatch:

env:
  EXE_NAME: sharpie

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

          - release_for: macOS-arm64
            os: macOS-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install fontconfig (Linux)
        if: runner.os == 'Linux'
        # Cache installed .debs across runs
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libfontconfig1-dev pkg-config
          version: 1.0

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Package and upload artifact
        uses: houseabsolute/actions-rust-release@v1
        with:
          executable-name: ${{ env.EXE_NAME }}
          target: ${{ matrix.platform.target }}
          changes-file: CHANGELOG.md

  release:
    needs: build
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: CSchoel/release-notes-from-changelog@v1
      - name: Create release from artifacts
        uses: houseabsolute/actions-rust-release/publish@v1
        with:
          executable-name: ${{ env.EXE_NAME }}
          changes-file: RELEASE.md
